eureka:
  instance:
    prefer-ip-address: true  # Corrected to 'instance' instead of 'instances'

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
